import type { Metadata } from "next";
import "@/styles/globals.scss";
import { Header, Layout } from "@/components";
import { Hanken_Grotesk } from "next/font/google";

const HankenGrotesk = Hanken_Grotesk({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: JSX.Element;
}>) {
  return (
    <html lang="en">
      <Layout>
        <main className={HankenGrotesk.className}>{children}</main>
      </Layout>
    </html>
  );
}
