import type { Metadata } from "next";
import "@/styles/globals.scss";
import { Header, Layout } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Layout>
        <main>{children}</main>
      </Layout>
    </html>
  );
}
