import type { Metadata } from "next";
import "@/styles/globals.scss";
import { Layout } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  auth,
  unauth,
}: Readonly<{
  children: React.ReactNode;
  auth: React.ReactNode;
  unauth: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Layout>{unauth}</Layout>
    </html>
  );
}
